export const IS_LOGGED_REQUEST = "IS_LOGGED_REQUEST";
export const IS_LOGGED_SUCCESS = "IS_LOGGED_SUCCESS";
export const IS_LOGGED_FAILURE = "IS_LOGGED_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";

export const FETCH_USER_DATA_REQUEST = "FETCH_USER_DATA_REQUEST";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";

export const SEND_VER_CODE_EMAIL_REQUEST = "SEND_VER_CODE_EMAIL_REQUEST";
export const SEND_VER_CODE_EMAIL_SUCCESS = "SEND_VER_CODE_EMAIL_SUCCESS";
export const SEND_VER_CODE_EMAIL_FAILURE = "SEND_VER_CODE_EMAIL_FAILURE";

export const CHECK_CODE_EMAIL_REQUEST = "CHECK_CODE_EMAIL_REQUEST";
export const CHECK_CODE_EMAIL_SUCCESS = "CHECK_CODE_EMAIL_SUCCESS";
export const CHECK_CODE_EMAIL_FAILURE = "CHECK_CODE_EMAIL_FAILURE";

export const UPDATE_USER_DATA_REQUEST = "UPDATE_USER_DATA_REQUEST";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_FAILURE = "UPDATE_USER_DATA_FAILURE";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const GET_INSTALL_REQUEST = "GET_INSTALL_REQUEST";
export const GET_INSTALL_SUCCESS = "GET_INSTALL_SUCCESS";
export const GET_INSTALL_FAILURE = "GET_INSTALL_FAILURE";

export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILURE = "CONTACT_US_FAILURE";

export const GET_HOME_REQUEST = "GET_HOME_REQUEST";
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS";
export const GET_HOME_FAILURE = "GET_HOME_FAILURE";

export const GET_FAV_REQUEST = "GET_FAV_REQUEST";
export const GET_FAV_SUCCESS = "GET_FAV_SUCCESS";
export const GET_FAV_FAILURE = "GET_FAV_FAILURE";

export const GET_FOODS_REQUEST = "GET_FOODS_REQUEST";
export const GET_FOODS_SUCCESS = "GET_FOODS_SUCCESS";
export const GET_FOODS_FAILURE = "GET_FOODS_FAILURE";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_MOST_ORDER_FOODS_REQUEST = "GET_MOST_ORDER_FOODS_REQUEST";
export const GET_MOST_ORDER_FOODS_SUCCESS = "GET_MOST_ORDER_FOODS_SUCCESS";
export const GET_MOST_ORDER_FOODS_FAILURE = "GET_MOST_ORDER_FOODS_FAILURE";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

export const TOGGLE_FAV_REQUEST = "TOGGLE_FAV_REQUEST";
export const TOGGLE_FAV_SUCCESS = "TOGGLE_FAV_SUCCESS";
export const TOGGLE_FAV_FAILURE = "TOGGLE_FAV_FAILURE";

export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAILURE = "GET_NOTIFICATIONS_FAILURE";

export const READ_NOTIFICATION_REQUEST = "READ_NOTIFICATION_REQUEST";
export const READ_NOTIFICATION_SUCCESS = "READ_NOTIFICATION_SUCCESS";
export const READ_NOTIFICATION_FAILURE = "READ_NOTIFICATION_FAILURE";

export const STORE_ORDER_REQUEST = "STORE_ORDER_REQUEST";
export const STORE_ORDER_SUCCESS = "STORE_ORDER_SUCCESS";
export const STORE_ORDER_FAILURE = "STORE_ORDER_FAILURE";

export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";

export const START_ORDER_REQUEST = "START_ORDER_REQUEST";
export const START_ORDER_SUCCESS = "START_ORDER_SUCCESS";
export const START_ORDER_FAILURE = "START_ORDER_FAILURE";

export const GET_LOCATIONS_REQUEST = "GET_LOCATIONS_REQUEST";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILURE = "GET_LOCATIONS_FAILURE";

export const ADD_LOCATION_REQUEST = "ADD_LOCATION_REQUEST";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILURE = "ADD_LOCATION_FAILURE";

export const GET_TICKETS_REQUEST = "GET_TICKETS_REQUEST";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_FAILURE = "GET_TICKETS_FAILURE";

export const RESPONSE_TICKETS_REQUEST = "RESPONSE_TICKETS_REQUEST";
export const RESPONSE_TICKETS_SUCCESS = "RESPONSE_TICKETS_SUCCESS";
export const RESPONSE_TICKETS_FAILURE = "RESPONSE_TICKETS_FAILURE";

export const GET_MORE_FOODS_REQUEST = "GET_MORE_FOODS_REQUEST";
export const GET_MORE_FOODS_SUCCESS = "GET_MORE_FOODS_SUCCESS";
export const GET_MORE_FOODS_FAILURE = "GET_MORE_FOODS_FAILURE";

export const HAS_PAYMENT_REQUEST = "HAS_PAYMENT_REQUEST";
export const HAS_PAYMENT_SUCCESS = "HAS_PAYMENT_SUCCESS";
export const HAS_PAYMENT_FAILURE = "HAS_PAYMENT_FAILURE";

export const ADD_PAYMENT_REQUEST = "ADD_PAYMENT_REQUEST";
export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_FAILURE = "ADD_PAYMENT_FAILURE";

export const SHOW_MODAL = "SHOW_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const LOGIN_GUEST = "LOGIN_GUEST";
